/*
 * Copyright (c) 2023.
 * Author Peter Placzek (tada5hi)
 * For the full copyright and license information,
 * view the LICENSE file that was distributed with this source code.
 */

import { readFileSync } from 'node:fs';
import type { UIOptions as SwaggerUIOptions } from '@routup/swagger-ui';
import { swaggerUI } from '@routup/swagger-ui';
import type { IApp, Plugin } from 'routup';
import { defineCoreHandler } from 'routup';
import type { Logger } from '@authup/server-kit';
import { normalizeError } from '@authup/errors';

/**
 * The key `x-authup-schema-hash` is written into the generated document at
 * build time, and holds the fingerprint of the query vocabulary the
 * document was generated for.
 */
const SCHEMA_HASH_KEY = 'x-authup-schema-hash';

type SwaggerMiddlewareOptions = SwaggerUIOptions & {
    documentPath: string,
    /**
     * The fingerprint of the query vocabulary this process serves. When it
     * disagrees with the one the document carries, the document is stale
     * and a warning says so. Omit it to skip the comparison.
     */
    schemaHash?: string,
    logger?: Logger
};

/**
 * Serve the Swagger UI at the mount path plus the raw document next to it,
 * at `<mount>/openapi.json`. The raw URL is the only machine-readable one:
 * `@routup/swagger-ui` inlines the document into its HTML shell and answers
 * every other path under the mount with that same shell, so a client that
 * wants the document itself has nowhere to fetch it from.
 *
 * Returns `undefined` when the document cannot be read, and the caller then
 * mounts nothing. `swaggerUI()` reads the file synchronously inside its own
 * `install`, and nothing catches that, so an absent document used to abort
 * the boot of the whole API. It is generated by a build step (`trapi
 * generate`) into a directory another build step wipes, so it goes missing
 * for ordinary reasons: an interrupted build, or `build:server:js` run on
 * its own. Documentation is not a precondition for serving an API.
 */
export function createSwaggerMiddleware(input: SwaggerMiddlewareOptions) : Plugin | undefined {
    const {
        documentPath, 
        schemaHash, 
        logger, 
        ...options
    } = input;

    let content : string;
    let document : Record<string, unknown>;

    try {
        content = readFileSync(documentPath, 'utf-8');
        document = JSON.parse(content);
    } catch (e) {
        logger?.warn(`The OpenAPI document ${documentPath} could not be read, so the documentation surface is not served. Build it with "npm run build". Reason: ${normalizeError(e).message}`);

        return undefined;
    }

    if (schemaHash) {
        const documentHash = document[SCHEMA_HASH_KEY];
        if (documentHash !== schemaHash) {
            const found = typeof documentHash === 'string' ? documentHash : 'none';

            // Under `authup dev` server-core runs from source while the
            // document is always the last built one, so this line is the
            // only signal that the two have drifted apart.
            logger?.warn(`The OpenAPI document ${documentPath} was generated for a different query vocabulary than this process serves (document: ${found}, runtime: ${schemaHash}). Rebuild it with "npm run build".`);
        }
    }

    return {
        name: 'swagger',
        install(router: IApp) {
            // Registered BEFORE the UI: that plugin answers every unmatched
            // path under the mount with its HTML shell, so a route declared
            // after it is never reached.
            router.get('/openapi.json', defineCoreHandler((event) => {
                event.response.headers.set('content-type', 'application/json; charset=utf-8');

                // The file verbatim rather than a re-serialization of the
                // parse above, so what is served is byte for byte what was
                // built. routup computes the ETag and answers a conditional
                // request from it.
                return content;
            }));

            swaggerUI(documentPath, options).install(router);
        },
    };
}
