/*
 * Copyright (c) 2025.
 * Author Peter Placzek (tada5hi)
 * For the full copyright and license information,
 * view the LICENSE file that was distributed with this source code.
 */

export const ConfigInjectionKey = Symbol('Config');

export enum ConfigEnvironmentVariableName {
    NODE_ENV = 'NODE_ENV',
    WRITABLE_DIRECTORY_PATH = 'WRITABLE_DIRECTORY_PATH',

    REDIS = 'REDIS',
    SMTP = 'SMTP',
    VAULT = 'VAULT',

    HOST = 'HOST',
    PORT = 'PORT',
    PUBLIC_URL = 'PUBLIC_URL',
    COOKIE_DOMAIN = 'COOKIE_DOMAIN',
    TOKEN_ACCESS_MAX_AGE = 'TOKEN_ACCESS_MAX_AGE',
    TOKEN_REFRESH_MAX_AGE = 'TOKEN_REFRESH_MAX_AGE',
    REGISTRATION = 'REGISTRATION',
    EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
    FORGOT_PASSWORD = 'FORGOT_PASSWORD',

    CLIENT_AUTH_BASIC = 'CLIENT_AUTH_BASIC',

    USER_AUTH_BASIC = 'USER_AUTH_BASIC',
    USER_ADMIN_ENABLED = 'USER_ADMIN_ENABLED',
    USER_ADMIN_PASSWORD = 'USER_ADMIN_PASSWORD',
    USER_ADMIN_PASSWORD_RESET = 'USER_ADMIN_PASSWORD_RESET',

    ROBOT_AUTH_BASIC = 'ROBOT_AUTH_BASIC',
    ROBOT_ADMIN_ENABLED = 'ROBOT_ADMIN_ENABLED',
    ROBOT_ADMIN_SECRET = 'ROBOT_ADMIN_SECRET',
    ROBOT_ADMIN_SECRET_RESET = 'ROBOT_ADMIN_SECRET_RESET',

    PERMISSIONS = 'PERMISSIONS',
}
