/*
 * Copyright (c) 2026.
 * Author Peter Placzek (tada5hi)
 * For the full copyright and license information,
 * view the LICENSE file that was distributed with this source code.
 */

import type { ClientSecretMode } from './constants';

/**
 * Body of `POST /clients/:id/secret`. A missing `secret` is generated by
 * the server; a missing `mode` keeps the client's current storage mode.
 */
export type ClientSecretRotatePayload = {
    secret?: string,
    mode?: `${ClientSecretMode}`,
};
