/*
 * Copyright (c) 2025.
 * Author Peter Placzek (tada5hi)
 * For the full copyright and license information,
 * view the LICENSE file that was distributed with this source code.
 */

import { TypedToken } from 'eldin';
import type { Config } from './types.ts';

export const ConfigInjectionKey = new TypedToken<Config>('Config');

export enum ConfigEnvironmentVariableName {
    NODE_ENV = 'NODE_ENV',
    WRITABLE_DIRECTORY_PATH = 'WRITABLE_DIRECTORY_PATH',

    REDIS = 'REDIS',
    SMTP = 'SMTP',

    HOST = 'HOST',
    PORT = 'PORT',
    PUBLIC_URL = 'PUBLIC_URL',
    TRUSTED_ORIGINS = 'TRUSTED_ORIGINS',
    TOKEN_ACCESS_MAX_AGE = 'TOKEN_ACCESS_MAX_AGE',
    TOKEN_REFRESH_MAX_AGE = 'TOKEN_REFRESH_MAX_AGE',
    TOKEN_REFRESH_GRACE_PERIOD = 'TOKEN_REFRESH_GRACE_PERIOD',
    PROMPT_LOGIN_MAX_AGE = 'PROMPT_LOGIN_MAX_AGE',
    END_SESSION_HINT_GRACE_PERIOD = 'END_SESSION_HINT_GRACE_PERIOD',
    REGISTRATION_ENABLED = 'REGISTRATION_ENABLED',
    EMAIL_VERIFICATION_ENABLED = 'EMAIL_VERIFICATION_ENABLED',
    PASSWORD_RECOVERY_ENABLED = 'PASSWORD_RECOVERY_ENABLED',
    PASSWORD_MIN_LENGTH = 'PASSWORD_MIN_LENGTH',

    EVENT_LOG_ENABLED = 'EVENT_LOG_ENABLED',
    EVENT_LOG_RETENTION_DAYS = 'EVENT_LOG_RETENTION_DAYS',
    EVENT_LOG_ENTITY_ENABLED = 'EVENT_LOG_ENTITY_ENABLED',
    EVENT_LOG_ENTITY_RETENTION_DAYS = 'EVENT_LOG_ENTITY_RETENTION_DAYS',
    LOGIN_ATTEMPT_THROTTLE_ENABLED = 'LOGIN_ATTEMPT_THROTTLE_ENABLED',
    LOGIN_ATTEMPT_THRESHOLD = 'LOGIN_ATTEMPT_THRESHOLD',
    LOGIN_ATTEMPT_WINDOW = 'LOGIN_ATTEMPT_WINDOW',

    MFA_ENABLED = 'MFA_ENABLED',
    MFA_REQUIRED = 'MFA_REQUIRED',
    MFA_ENCRYPTION_KEY = 'MFA_ENCRYPTION_KEY',

    CLIENT_AUTH_BASIC = 'CLIENT_AUTH_BASIC',
    CLIENT_SYSTEM_ENABLED = 'CLIENT_SYSTEM_ENABLED',
    CLIENT_SYSTEM_SECRET = 'CLIENT_SYSTEM_SECRET',
    CLIENT_SYSTEM_SECRET_RESET = 'CLIENT_SYSTEM_SECRET_RESET',

    USER_AUTH_BASIC = 'USER_AUTH_BASIC',
    USER_ADMIN_ENABLED = 'USER_ADMIN_ENABLED',
    USER_ADMIN_PASSWORD = 'USER_ADMIN_PASSWORD',
    USER_ADMIN_PASSWORD_RESET = 'USER_ADMIN_PASSWORD_RESET',

    ROBOT_AUTH_BASIC = 'ROBOT_AUTH_BASIC',
    ROBOT_ADMIN_ENABLED = 'ROBOT_ADMIN_ENABLED',
    ROBOT_ADMIN_SECRET = 'ROBOT_ADMIN_SECRET',
    ROBOT_ADMIN_SECRET_RESET = 'ROBOT_ADMIN_SECRET_RESET',

    PERMISSIONS = 'PERMISSIONS',
    PERMISSIONS_DEFAULT_POLICY_ASSIGNMENT = 'PERMISSIONS_DEFAULT_POLICY_ASSIGNMENT',
}
