#!/usr/bin/env sh
#
# Copyright (c) 2023.
# Author Peter Placzek (tada5hi) 
# For the full copyright and license information,
# view the LICENSE file that was distributed with this source code.
#

. "$(dirname -- "$0")/_/husky.sh"

npx --no -- commitlint --edit 
