name: docker-nightly

on:
    schedule:
        - cron: "0 0 * * *"

jobs:
    push:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read

        steps:
            -   uses: actions/checkout@v5

            -   uses: tada5hi/action-docker-image-publish@v3
                with:
                    cleanup: false
                    registryRepository: authup/authup
                    registryTag: next

            -   uses: tada5hi/action-docker-image-publish@v3
                with:
                    registryHost: docker.io
                    registryRepository: authup/authup
                    registryUser: authup
                    registryTag: next
                    registryPassword: ${{ secrets.DOCKER_HUB_TOKEN }}


